run mypy from @sfpi which contains the mypy.ini config file:
@sfpi> mypy src  should work since dir search is SUPPOSED to be RECURSIVE.
However search is NOT RECURSIVE - finds ONLY src/sfpi.py - BUG!!!


instead use:
@sfpi> mypy src src/**/*.py
expect: Success: no issues found in 11 source files


NOTE: to also check files in test use:
@sfpi> mypy test src src/**/*.py
expect: Success: no issues found in 14 source files
